batch_size:
  value: 4
lr:
  value: 0.001
img_size:
  value: 256
n_vertices:
  value: 1000 # 100
n_epochs:
  value: 100
resize_size:
  value : 224
checkpoint_path:
  value: "" #checkpoints/save.pt
patch_embed_dim:
  value: 124